services:
  postgres:
    image: postgres:17.2-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: idea_forge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: